name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Укажите master, если ваша основная ветка называется так

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Папка, куда Vite собирает готовый проект
          branch: gh-pages # Ветка, куда запишется результат сборки
